<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';
commonHeaders();
$user=requireAuth();
if(!in_array((string)($user['role']??''),['administrator','projektleiter','pruefer','sachverstaendiger'],true))apiError(403,'Keine Berechtigung.');
db()->exec("CREATE TABLE IF NOT EXISTS claimsforce_import_jobs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,profile VARCHAR(30) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'queued',requested_by VARCHAR(255) NOT NULL,message VARCHAR(500) NULL,result_json MEDIUMTEXT NULL,created_at DATETIME NOT NULL,started_at DATETIME NULL,finished_at DATETIME NULL,INDEX idx_claims_queue(status,created_at),INDEX idx_claims_user(requested_by,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
function cqProfile(array$user):string{$email=mb_strtolower((string)($user['email']??''),'UTF-8');$name=mb_strtolower((string)($user['full_name']??''),'UTF-8');if(str_contains($email,'hr@')||str_contains($name,'holger'))return'holger';if(str_contains($email,'ms@')||str_contains($name,'marc'))return'marc';return'christian';}
function cqRow(int$id):array{$s=db()->prepare('SELECT id,profile,status,message,result_json,created_at,started_at,finished_at,requested_by FROM claimsforce_import_jobs WHERE id=:id LIMIT 1');$s->execute([':id'=>$id]);return$s->fetch(PDO::FETCH_ASSOC)?:[];}
$action=(string)($_GET['action']??'status');$body=$_SERVER['REQUEST_METHOD']==='POST'?requestBody():[];
if($action==='enqueue'){$profile=cqProfile($user);if(($user['role']??'')==='administrator'&&in_array((string)($body['profile']??''),['christian','holger','marc'],true))$profile=(string)$body['profile'];$s=db()->prepare("INSERT INTO claimsforce_import_jobs(profile,status,requested_by,message,created_at) VALUES(:p,'queued',:u,'Import wartet auf die zentrale Importstation.',NOW())");$s->execute([':p'=>$profile,':u'=>(string)($user['email']??'')]);apiJson(['ok'=>true,'job'=>cqRow((int)db()->lastInsertId())]);}
if($action==='status'){$row=cqRow((int)($_GET['id']??0));if(!$row)apiError(404,'Importauftrag nicht gefunden.');if(($user['role']??'')!=='administrator'&&!hash_equals((string)($user['email']??''),(string)$row['requested_by']))apiError(403,'Keine Berechtigung.');unset($row['requested_by']);apiJson(['ok'=>true,'job'=>$row]);}
if(($user['role']??'')!=='administrator')apiError(403,'Nur die zentrale Importstation darf Aufträge übernehmen.');
if($action==='claim'){db()->beginTransaction();$row=db()->query("SELECT id FROM claimsforce_import_jobs WHERE status='queued' ORDER BY created_at,id LIMIT 1 FOR UPDATE")->fetch(PDO::FETCH_ASSOC);if(!$row){db()->commit();apiJson(['ok'=>true,'job'=>null]);}$id=(int)$row['id'];$s=db()->prepare("UPDATE claimsforce_import_jobs SET status='running',message='Import wird auf der zentralen Station ausgeführt.',started_at=NOW() WHERE id=:id AND status='queued'");$s->execute([':id'=>$id]);db()->commit();apiJson(['ok'=>true,'job'=>cqRow($id)]);}
if($action==='complete'){$id=(int)($body['id']??0);$ok=($body['ok']??false)===true;$message=mb_substr(trim((string)($body['message']??($ok?'Import abgeschlossen.':'Import fehlgeschlagen.'))),0,500);$s=db()->prepare("UPDATE claimsforce_import_jobs SET status=:s,message=:m,result_json=:r,finished_at=NOW() WHERE id=:id AND status='running'");$s->execute([':s'=>$ok?'done':'failed',':m'=>$message,':r'=>json_encode($body['result']??null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':id'=>$id]);apiJson(['ok'=>true,'job'=>cqRow($id)]);}
apiError(404,'Unbekannte Aktion.');
