<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
commonHeaders();
$user=requireAuth();
if(!in_array($user['role']??'', ['administrator','projektleiter','pruefer','sachverstaendiger'], true)) apiError(403,'Keine Berechtigung.');

const GF_SRC_KNOWLEDGE='1QeJ4Dz6Upg_W5rahWmKE_7KbC4MMgSGe';
const GF_SRC_BLANCO='1_3p6moLBt3cD5Gzy9jvPw3BXpqnAvl2k';

function sGet(string $key,string $default=''):string{try{$stmt=db()->prepare('SELECT setting_value FROM app_settings WHERE setting_key=:k LIMIT 1');$stmt->execute([':k'=>$key]);$v=$stmt->fetchColumn();return $v===false?$default:(string)$v;}catch(Throwable $e){return $default;}}
function b64u(string $s):string{return rtrim(strtr(base64_encode($s),'+/','-_'),'=');}
function httpx(string $method,string $url,array $headers=[],?string $body=null,bool $auth=true):array{if($auth)$headers[]='Authorization: Bearer '.token();$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>90,CURLOPT_FOLLOWLOCATION=>true]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,$body);$r=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($r===false||$err!=='')apiError(503,'Google-Drive-Verbindung fehlgeschlagen: '.($err?:'unbekannter Fehler'));return['status'=>$status,'body'=>(string)$r];}
function token():string{static $t=null;if($t!==null)return$t;$svcJson=trim(env('GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON',''));if($svcJson!==''){if(!str_starts_with($svcJson,'{')){$d=base64_decode($svcJson,true);if($d!==false)$svcJson=$d;}$svc=json_decode($svcJson,true);if(is_array($svc)&&!empty($svc['client_email'])&&!empty($svc['private_key'])){$now=time();$h=b64u(json_encode(['alg'=>'RS256','typ'=>'JWT']));$c=b64u(json_encode(['iss'=>$svc['client_email'],'scope'=>'https://www.googleapis.com/auth/drive','aud'=>'https://oauth2.googleapis.com/token','iat'=>$now,'exp'=>$now+3500]));$in=$h.'.'.$c;$sig='';if(openssl_sign($in,$sig,$svc['private_key'],OPENSSL_ALGO_SHA256)){$jwt=$in.'.'.b64u($sig);$r=httpx('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt]),false);$j=json_decode($r['body'],true);if($r['status']===200&&!empty($j['access_token']))return$t=(string)$j['access_token'];}}}$cid=env('GOOGLE_DRIVE_CLIENT_ID',sGet('google_drive_client_id'));$sec=env('GOOGLE_DRIVE_CLIENT_SECRET',sGet('google_drive_client_secret'));$ref=env('GOOGLE_DRIVE_REFRESH_TOKEN',sGet('google_drive_refresh_token'));if($cid!==''&&$sec!==''&&$ref!==''){$r=httpx('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['client_id'=>$cid,'client_secret'=>$sec,'refresh_token'=>$ref,'grant_type'=>'refresh_token']),false);$j=json_decode($r['body'],true);if($r['status']===200&&!empty($j['access_token']))return$t=(string)$j['access_token'];}apiError(503,'Google Drive ist nicht verbunden.');}
function children(string $parent):array{$q="'".str_replace("'","\\'",$parent)."' in parents and trashed=false";$url='https://www.googleapis.com/drive/v3/files?'.http_build_query(['q'=>$q,'fields'=>'files(id,name,mimeType,modifiedTime,size,webViewLink)','pageSize'=>1000,'supportsAllDrives'=>'true']);$r=httpx('GET',$url);if($r['status']!==200)apiError(503,'Google-Drive-Quellen konnten nicht gelesen werden.');$j=json_decode($r['body'],true);return is_array($j['files']??null)?$j['files']:[];}
function supported(array $f):bool{$m=(string)($f['mimeType']??'');$n=mb_strtolower((string)($f['name']??''),'UTF-8');if($m==='application/vnd.google-apps.folder')return false;if(str_starts_with($m,'application/vnd.google-apps.'))return in_array($m,['application/vnd.google-apps.document','application/vnd.google-apps.spreadsheet'],true);return preg_match('/\.(pdf|docx?|xlsx?|xlsm|csv|txt|md|rtf)$/ui',$n)===1||str_starts_with($m,'text/')||str_contains($m,'pdf')||str_contains($m,'word')||str_contains($m,'sheet');}
function walk(string $root,int $maxDepth=6,int $maxFiles=250):array{$out=[];$queue=[[$root,'',0]];while($queue&&count($out)<$maxFiles){[$parent,$path,$depth]=array_shift($queue);foreach(children($parent) as$f){$name=(string)($f['name']??'');$p=ltrim($path.'/'.$name,'/');if(($f['mimeType']??'')==='application/vnd.google-apps.folder'){if($depth<$maxDepth)$queue[]=[(string)$f['id'],$p,$depth+1];continue;}if(!supported($f))continue;$f['path']=$p;$out[]=$f;if(count($out)>=$maxFiles)break;}}return$out;}
$knowledge=walk(GF_SRC_KNOWLEDGE);$blanco=walk(GF_SRC_BLANCO);
apiJson(['ok'=>true,'knowledge'=>$knowledge,'blanco'=>$blanco,'knowledge_count'=>count($knowledge),'blanco_count'=>count($blanco)]);
