<?php
declare(strict_types=1);

require_once __DIR__ . '/config.php';
commonHeaders();
$user = requireAuth();
if (!in_array($user['role'], ['administrator','projektleiter','pruefer','sachverstaendiger'], true)) {
    apiError(403, 'Keine Berechtigung.');
}

const DEFAULT_CASES_FOLDER_ID = '1dqdQkccdGLuo8ijKerGgYdmNO2cBtD4P';
const DEFAULT_KNOWLEDGE_FOLDER_ID = '1QeJ4Dz6Upg_W5rahWmKE_7KbC4MMgSGe';
const DEFAULT_BLANCO_FOLDER_ID = '1_3p6moLBt3cD5Gzy9jvPw3BXpqnAvl2k';
const CASE_META_NAME = '00_Falldaten.json';

$action = (string)($_GET['action'] ?? 'status');

function gdIsSusanne(array $user):bool{$email=gdUserKey($user);$name=gdNormalize((string)($user['full_name']??''));return str_contains($email,'susanne')||str_contains($name,'susanne waechter');}
function gdExpertIdentity(string $key,array $backoffice):array{return match($key){'holger'=>array_merge($backoffice,['email'=>'hr@sv-schuett.eu','full_name'=>'Holger Roth']),'marc'=>array_merge($backoffice,['email'=>'ms@sv-schuett.eu','full_name'=>'Marc Schütt']),default=>array_merge($backoffice,['email'=>'cw@sv-netzwerk.eu','full_name'=>'Christian Wächter'])};}

$portalUser=$user;
$isBackoffice=gdIsSusanne($portalUser);
if($isBackoffice&&$action==='select_expert'){
    if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');
    $body=requestBody();$expert=(string)($body['expert']??'christian');
    if(!in_array($expert,['christian','holger','marc'],true))apiError(400,'Unbekannter Sachverständiger.');
    $_SESSION['svnet_selected_expert']=$expert;
    apiJson(['ok'=>true,'expert'=>$expert]);
}
$selectedExpert=$isBackoffice?(string)($_SESSION['svnet_selected_expert']??'christian'):'';
if($isBackoffice)$user=gdExpertIdentity($selectedExpert,$portalUser);

function gdSettingGet(string $key, string $default=''): string {
    try {
        db()->exec("CREATE TABLE IF NOT EXISTS app_settings (
            setting_key VARCHAR(190) PRIMARY KEY,
            setting_value MEDIUMTEXT NULL,
            updated_at DATETIME NOT NULL,
            updated_by VARCHAR(190) NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $stmt=db()->prepare('SELECT setting_value FROM app_settings WHERE setting_key=:k LIMIT 1');
        $stmt->execute([':k'=>$key]);
        $value=$stmt->fetchColumn();
        return $value===false ? $default : (string)$value;
    } catch(Throwable $e) {
        error_log('[google-drive-sync] setting read failed: '.$e->getMessage());
        return $default;
    }
}

function gdB64url(string $data): string { return rtrim(strtr(base64_encode($data), '+/', '-_'), '='); }

function gdAccessToken(): string {
    static $token = null;
    if ($token !== null) return $token;
    $serviceJson = trim(env('GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON', ''));
    if ($serviceJson !== '') {
        if (!str_starts_with($serviceJson, '{')) {
            $decoded = base64_decode($serviceJson, true);
            if ($decoded !== false) $serviceJson = $decoded;
        }
        $svc = json_decode($serviceJson, true);
        if (is_array($svc) && !empty($svc['client_email']) && !empty($svc['private_key'])) {
            $now = time();
            $header = gdB64url(json_encode(['alg'=>'RS256','typ'=>'JWT'], JSON_UNESCAPED_SLASHES));
            $claims = gdB64url(json_encode(['iss'=>$svc['client_email'],'scope'=>'https://www.googleapis.com/auth/drive','aud'=>'https://oauth2.googleapis.com/token','iat'=>$now,'exp'=>$now + 3500], JSON_UNESCAPED_SLASHES));
            $input = $header . '.' . $claims;$signature='';
            if (!openssl_sign($input, $signature, $svc['private_key'], OPENSSL_ALGO_SHA256)) apiError(503, 'Google-Drive-Servicekonto konnte nicht signieren.');
            $jwt=$input.'.'.gdB64url($signature);
            $resp=gdHttp('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt]),false);
            $body=json_decode($resp['body'],true);
            if ($resp['status']===200 && !empty($body['access_token'])) return $token=(string)$body['access_token'];
        }
    }
    $clientId=env('GOOGLE_DRIVE_CLIENT_ID',gdSettingGet('google_drive_client_id'));
    $clientSecret=env('GOOGLE_DRIVE_CLIENT_SECRET',gdSettingGet('google_drive_client_secret'));
    $refreshToken=env('GOOGLE_DRIVE_REFRESH_TOKEN',gdSettingGet('google_drive_refresh_token'));
    if ($clientId!=='' && $clientSecret!=='' && $refreshToken!=='') {
        $resp=gdHttp('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['client_id'=>$clientId,'client_secret'=>$clientSecret,'refresh_token'=>$refreshToken,'grant_type'=>'refresh_token']),false);
        $body=json_decode($resp['body'],true);
        if ($resp['status']===200 && !empty($body['access_token'])) return $token=(string)$body['access_token'];
    }
    apiError(503, 'Google Drive ist noch nicht verbunden. Bitte im Versicherungsportal „Mit Google Drive verbinden“ verwenden.');
}

function gdHttp(string $method,string $url,array $headers=[],?string $body=null,bool $auth=true): array {
    if ($auth) $headers[]='Authorization: Bearer '.gdAccessToken();
    $ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_CONNECTTIMEOUT=>12,CURLOPT_TIMEOUT=>90,CURLOPT_FOLLOWLOCATION=>true]);
    if ($body!==null) curl_setopt($ch,CURLOPT_POSTFIELDS,$body);
    $response=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);
    if ($response===false || $err!=='') apiError(503,'Google-Drive-Verbindung fehlgeschlagen: '.($err?:'unbekannter Fehler'));
    return ['status'=>$status,'body'=>(string)$response];
}
function gdApi(string $method,string $path,array $query=[],?array $json=null): array {$url='https://www.googleapis.com/drive/v3/'.ltrim($path,'/');$query+=['supportsAllDrives'=>'true'];if($query)$url.='?'.http_build_query($query);$headers=[];$body=null;if($json!==null){$headers[]='Content-Type: application/json; charset=utf-8';$body=json_encode($json,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}$resp=gdHttp($method,$url,$headers,$body,true);$data=json_decode($resp['body'],true);if($resp['status']<200||$resp['status']>=300)apiError(503,'Google-Drive-API-Fehler ('.$resp['status'].').');return is_array($data)?$data:[];}
function gdFolderId(string $kind): string {return match($kind){'cases'=>env('GOOGLE_DRIVE_CASES_FOLDER_ID',DEFAULT_CASES_FOLDER_ID),'knowledge'=>env('GOOGLE_DRIVE_KNOWLEDGE_FOLDER_ID',DEFAULT_KNOWLEDGE_FOLDER_ID),'blanco'=>env('GOOGLE_DRIVE_BLANCO_FOLDER_ID',DEFAULT_BLANCO_FOLDER_ID),default=>''};}
function gdEscape(string $v): string{return str_replace("'","\\'",$v);}function gdListChildren(string $parentId,?string $mime=null,int $limit=1000):array{$q="'".gdEscape($parentId)."' in parents and trashed=false";if($mime!==null)$q.=" and mimeType='".gdEscape($mime)."'";$out=[];$pageToken='';do{$query=['q'=>$q,'fields'=>'nextPageToken,files(id,name,mimeType,modifiedTime,createdTime,size,webViewLink,parents,appProperties)','pageSize'=>min(1000,$limit-count($out)),'orderBy'=>'name_natural'];if($pageToken!=='')$query['pageToken']=$pageToken;$data=gdApi('GET','files',$query);foreach(($data['files']??[])as$f)$out[]=$f;$pageToken=(string)($data['nextPageToken']??'');}while($pageToken!==''&&count($out)<$limit);return$out;}
function gdFileMeta(string $fileId):array{return gdApi('GET','files/'.rawurlencode($fileId),['fields'=>'id,name,mimeType,parents,trashed']);}
function gdDownload(string $fileId):string{$resp=gdHttp('GET','https://www.googleapis.com/drive/v3/files/'.rawurlencode($fileId).'?alt=media&supportsAllDrives=true',[],null,true);if($resp['status']!==200)apiError(503,'Google-Drive-Datei konnte nicht geladen werden.');return$resp['body'];}
function gdCreateFolder(string $parentId,string $name):array{return gdApi('POST','files',['fields'=>'id,name,webViewLink'],['name'=>$name,'mimeType'=>'application/vnd.google-apps.folder','parents'=>[$parentId]]);}function gdFindChildByName(string $parentId,string $name):?array{$q="'".gdEscape($parentId)."' in parents and trashed=false and name='".gdEscape($name)."'";$data=gdApi('GET','files',['q'=>$q,'fields'=>'files(id,name,mimeType,modifiedTime,webViewLink)','pageSize'=>20]);return!empty($data['files'][0])?$data['files'][0]:null;}
function gdUserKey(array $user):string{return strtolower(trim((string)($user['email']??'')));}
function gdIsMarc(array $user):bool{$email=gdUserKey($user);$name=gdNormalize((string)($user['full_name']??''));return $email==='ms@sv-schuett.eu'||str_contains($name,'marc schuett');}
function gdIsHolger(array $user):bool{$email=gdUserKey($user);$name=gdNormalize((string)($user['full_name']??''));return $email==='hr@sv-schuett.eu'||str_contains($name,'holger roth');}
function gdUserCasesName(array $user):string{$name=trim((string)($user['full_name']??''));if($name===''){$local=explode('@',gdUserKey($user),2)[0]??'Benutzer';$name=preg_replace('/[^a-z0-9._-]+/i',' ',(string)$local)?:'Benutzer';}return'Schadenfälle '.$name;}
function gdUserCasesRoot(array $user):array{$legacy=gdFolderId('cases');if(!gdIsMarc($user)&&!gdIsHolger($user))return['id'=>$legacy,'name'=>'Schadenfälle Christian Wächter'];$meta=gdFileMeta($legacy);$parent=trim((string)(($meta['parents']??[])[0]??''));if($parent==='')apiError(503,'Der persönliche Schadenfälle-Ordner kann nicht angelegt werden: Übergeordneter Drive-Ordner fehlt.');$name=gdIsMarc($user)?'Schadenfälle Marc Schütt':'Schadenfälle Holger Roth';$folder=gdFindChildByName($parent,$name);if(!$folder||($folder['mimeType']??'')!=='application/vnd.google-apps.folder')$folder=gdCreateFolder($parent,$name);return['id'=>(string)$folder['id'],'name'=>$name];}
function gdEnsureKnownCasesRoots():void{$legacy=gdFolderId('cases');$meta=gdFileMeta($legacy);$parent=trim((string)(($meta['parents']??[])[0]??''));if($parent==='')return;foreach(['Schadenfälle Holger Roth','Schadenfälle Marc Schütt']as$name){$folder=gdFindChildByName($parent,$name);if(!$folder||($folder['mimeType']??'')!=='application/vnd.google-apps.folder')gdCreateFolder($parent,$name);}}
function gdAssertCaseAccess(string $caseId,array $user):void{if($caseId==='')apiError(400,'Kein aktiver Fallordner.');$root=gdUserCasesRoot($user);$folder=gdFileMeta($caseId);if(($folder['mimeType']??'')!=='application/vnd.google-apps.folder'||!in_array((string)$root['id'],$folder['parents']??[],true))apiError(403,'Dieser Schadenfall gehört zu einem anderen Benutzer und darf nicht geöffnet oder verändert werden.');registerCaseFolderOwner($caseId,$user,gdCaseMeta($caseId));}
function gdUploadJson(string $parentId,string $name,array $payload):array{$existing=gdFindChildByName($parentId,$name);$meta=['name'=>$name,'mimeType'=>'application/json'];if(!$existing)$meta['parents']=[$parentId];$boundary='svnet'.bin2hex(random_bytes(8));$body='--'.$boundary."\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n".json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\r\n--".$boundary."\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n".json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\r\n--".$boundary."--";$method=$existing?'PATCH':'POST';$url='https://www.googleapis.com/upload/drive/v3/files'.($existing?'/'.rawurlencode($existing['id']):'').'?uploadType=multipart&supportsAllDrives=true&fields=id,name,modifiedTime,webViewLink';$resp=gdHttp($method,$url,['Content-Type: multipart/related; boundary='.$boundary],$body,true);if($resp['status']<200||$resp['status']>=300)apiError(503,'Falldaten konnten nicht in Google Drive gespeichert werden.');return json_decode($resp['body'],true)?:[];}
function gdUploadBytes(string $parentId,string $name,string $mime,string $bytes):array{$meta=['name'=>$name,'mimeType'=>$mime,'parents'=>[$parentId]];$boundary='svnet'.bin2hex(random_bytes(8));$body='--'.$boundary."\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n".json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\r\n--".$boundary."\r\nContent-Type: ".$mime."\r\n\r\n".$bytes."\r\n--".$boundary."--";$url='https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id,name,mimeType,modifiedTime,webViewLink,webContentLink';$resp=gdHttp('POST',$url,['Content-Type: multipart/related; boundary='.$boundary],$body,true);if($resp['status']<200||$resp['status']>=300)apiError(503,'Dokument konnte nicht in Google Drive gespeichert werden.');return json_decode($resp['body'],true)?:[];}
function gdCaseFolders():array{return['01_Auftrag_Grundlagen','02_Fotos','03_Plaene_Technik','04_Rechnungen_KVA','05_Berichte_Nachtraege','06_Freigaben_Zahlungen','07_Korrespondenz','08_Abschluss'];}
function gdCaseCategory(string $name,string $mime=''):string{$n=gdNormalize($name);if(str_starts_with($mime,'image/')||preg_match('/\b(foto|fotos|bild|bilder|aufnahme|img|image)\b/u',$n))return'02_Fotos';if(preg_match('/\b(plan|plaene|zeichnung|technik|leckort|messprotokoll|trocknung|grundriss|statik)\b/u',$n))return'03_Plaene_Technik';if(preg_match('/\b(rechnung|abschlagsrechnung|teilrechnung|schlussrechnung|honorarrechnung|kva|kostenvoranschlag|kostenanschlag|schaetzung|angebot)\b/u',$n))return'04_Rechnungen_KVA';if(preg_match('/\b(abschluss|schlusserklaerung|schlussbericht|erledigt)\b/u',$n))return'08_Abschluss';if(preg_match('/\b(bericht|gutachten|nachtrag|stellungnahme|protokoll|dokumentenindex|rechnungsregister)\b/u',$n))return'05_Berichte_Nachtraege';if(preg_match('/\b(freigabe|zahlung|zahlungsbefuerwortung|vorauszahlung|abrechnung|entschaedigung)\b/u',$n))return'06_Freigaben_Zahlungen';if(preg_match('/\b(mail|email|e mail|brief|schreiben|korrespondenz|antwort|anfrage|rueckfrage)\b/u',$n)||in_array($mime,['message/rfc822','application/vnd.ms-outlook'],true))return'07_Korrespondenz';return'01_Auftrag_Grundlagen';}
function gdOriginalCaseName(string $name):string{return preg_replace('/^(?:Fallakte|Unterlage|Gutachten|KVA|Rechnung|Schriftverkehr|Mail)_\d{4}-\d{2}-\d{2}_\d{6}_(.+)$/u','$1',$name)??$name;}
function gdEnsureCaseFolder(string $caseId,string $name):array{$found=gdFindChildByName($caseId,$name);return$found&&($found['mimeType']??'')==='application/vnd.google-apps.folder'?$found:gdCreateFolder($caseId,$name);}
function gdExcludedCaseAsset(string $name,string $mime,string $bytes):?string{
    if(!str_starts_with(strtolower($mime),'image/'))return null;
    $hash=hash('sha256',$bytes);
    $knownHashes=[
        'd7e3662266444a6b1dd36cbb9a95546066eeae0d920a6f702ae716ba8aacb0cf',
        '102f119c25022500542ab12d312602666f7e210bfbe067170fa15b6a69899880',
        '008eabe9fac31bc3a22473dcd52b287630b8d7bdc4added8cd01aa47c73f9431',
        'a3ea5a503049dff4515211b7d41aba2f4e1ee33666df00a36a10fc862da3b1dc'
    ];
    if(in_array($hash,$knownHashes,true))return'Bekannte Signatur-, Profil- oder Systemgrafik';
    $normalized=gdNormalize($name);
    $knownNames=[
        'bvslogo2 7ce28f0c 700d 454c b645 db96d1c775fb',
        'chatgptimage9 aug 2026 19 01 28 4631f03f 1db8 414c a636 9b7ee544d6e1',
        'klein 353f6da3 e1b8 46b3 9797 b35ae37e31b4',
        'teams 32x32 9178119f 105b 4f5c abab a3ecadf7ea7c',
        'teams 32x32 91084020 9e25 41aa b1a1 6681281811c7'
    ];
    foreach($knownNames as$known)if(str_contains($normalized,$known))return'Bekannte Signatur-, Profil- oder Systemgrafik';
    return null;
}
function gdUploadCaseFile(string $folderId,string $name,string $mime,string $bytes,int $originalModified):array{$category=gdCaseCategory($name,$mime);$target=gdEnsureCaseFolder($folderId,$category);$targetId=(string)$target['id'];$size=strlen($bytes);foreach(gdListChildren($targetId,null,1000)as$item){if((string)($item['name']??'')!==$name||(int)($item['size']??-1)!==$size)continue;$saved=(int)($item['appProperties']['svOriginalModified']??0);if($saved===$originalModified)return['duplicate'=>true,'category'=>$category,'file'=>$item];}$meta=['name'=>$name,'mimeType'=>$mime,'parents'=>[$targetId],'appProperties'=>['svOriginalModified'=>(string)$originalModified]];$boundary='svnet'.bin2hex(random_bytes(8));$body='--'.$boundary."\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n".json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\r\n--".$boundary."\r\nContent-Type: ".$mime."\r\n\r\n".$bytes."\r\n--".$boundary."--";$url='https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id,name,mimeType,size,modifiedTime,webViewLink,webContentLink,appProperties';$resp=gdHttp('POST',$url,['Content-Type: multipart/related; boundary='.$boundary],$body,true);if($resp['status']<200||$resp['status']>=300)apiError(503,'Dokument konnte nicht in Google Drive gespeichert werden.');return['duplicate'=>false,'category'=>$category,'file'=>json_decode($resp['body'],true)?:[]];}
function gdOrganizeCase(string $caseId):array{$folders=[];foreach(gdCaseFolders()as$name){$f=gdEnsureCaseFolder($caseId,$name);$folders[$name]=(string)$f['id'];}$moved=0;$ignored=0;foreach(gdListChildren($caseId,null,1000)as$file){if(($file['mimeType']??'')==='application/vnd.google-apps.folder'||in_array((string)($file['name']??''),[CASE_META_NAME,'00_FALLINDEX.md'],true)){$ignored++;continue;}$oldName=(string)($file['name']??'');$name=gdOriginalCaseName($oldName);$category=gdCaseCategory($name,(string)($file['mimeType']??''));$id=(string)($file['id']??'');if($id==='')continue;$query=['addParents'=>$folders[$category],'removeParents'=>$caseId,'fields'=>'id,name,parents'];$body=$name!==$oldName?['name'=>$name]:null;gdApi('PATCH','files/'.rawurlencode($id),$query,$body);$moved++;}return['moved'=>$moved,'ignored'=>$ignored];}
function gdEnsureCaseExcelForms(string $folderId):array{$templates=gdListChildren(gdFolderId('blanco'),null,1000);$wanted=['Schlusserklärung.xlsm'=>'00_Original_Schlusserklärung.xlsm','Zahlungsbefürwortung.xlsm'=>'00_Original_Zahlungsbefürwortung.xlsm'];$result=[];foreach($wanted as$templateName=>$caseName){$existing=gdFindChildByName($folderId,$caseName);if($existing){$result[]=$existing;continue;}$template=null;foreach($templates as$item)if(strcasecmp((string)($item['name']??''),$templateName)===0){$template=$item;break;}if(!$template)apiError(503,'Excel-Originalformular nicht gefunden: '.$templateName);$result[]=gdUploadBytes($folderId,$caseName,'application/vnd.ms-excel.sheet.macroenabled.12',gdDownload((string)$template['id']));}return$result;}
function gdNormalize(string $s):string{$s=mb_strtolower(trim($s),'UTF-8');$s=strtr($s,['ä'=>'ae','ö'=>'oe','ü'=>'ue','ß'=>'ss']);return preg_replace('/[^a-z0-9]+/u',' ',$s)??'';}function gdCaseMeta(string $folderId):array{$metaFile=gdFindChildByName($folderId,CASE_META_NAME);if(!$metaFile)return[];$data=json_decode(gdDownload((string)$metaFile['id']),true);return is_array($data)?$data:[];}function gdCaseName(array $d):string{$parts=[];foreach(['schaden_nr','vn_objekt','ort']as$key){$v=trim((string)($d[$key]??''));if($v!=='')$parts[]=$v;}$name=implode(' - ',$parts);return$name!==''?mb_substr($name,0,180):'Versicherungsfall '.date('Y-m-d H-i');}function gdH(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function gdSafeName(string $v):string{$v=preg_replace('/[^A-Za-z0-9ÄÖÜäöüß._-]+/u','-',trim($v))??'';return trim($v,'-_.')?:'Fall';}
function gfOutputTitle(string $key):string{return match($key){'erstbericht'=>'Erstbericht','schadenprotokoll'=>'Schadenprotokoll','schlusserklaerung'=>'Schlusserklärung','zahlungsbefuerwortung'=>'Zahlungsbefürwortung','nachtrag_stellungnahme'=>'Nachtrag-Stellungnahme','zwischenbericht'=>'Zwischenbericht','schlussbericht'=>'Schlussbericht','vorauszahlung'=>'Vorauszahlung-Freigabe','query_form'=>'Rückfrageformular',default=>'Dokument'};}
function gfSections(string $key):array{return match($key){'erstbericht'=>['Versicherungsverhältnisse','Risikoverhältnisse','Schadenhergang / Schadenursache','Polizeiliche / behördliche Ermittlungen','Ersatzpflicht / Deckung','Schadenumfang','Reserve und Schadenhöhe','Schadenabwicklung','Teilzahlung / Vorauszahlung','Regress'],'schadenprotokoll'=>['Schadenort und Besichtigungsdaten','Anwesende Personen','Schadenhergang','Festgestelltes Schadenbild','Ursache','Betroffene Bereiche / Sachen','Sofortmaßnahmen','Unterlagen / Belege','Erklärungen des Versicherungsnehmers','Unterschriften / Vermerk'],'schlusserklaerung'=>['Schadenermittlung','Einzelmengen und Positionen','Abzüge / Selbstbehalt','Bereits geleistete Zahlungen','Entschädigungsbetrag','Restreserve','Erklärung / Unterschrift'],'zahlungsbefuerwortung'=>['Zahlungsempfänger','Betrag','Zahlungsgrund','Geprüfte Unterlagen','Bereits geleistete Zahlungen','Restreserve','Befürwortung'],'nachtrag_stellungnahme'=>['Bezug / bisheriger Prüfstand','Neu vorliegende Unterlage / Gutachten','Bisherige Zweifel / offene Punkte','Neue fachliche Feststellungen','Bewertung des Kostenvoranschlags','Entscheidung / Empfehlung','Unterrichtung des Versicherungsnehmers durch die SV','Auswirkungen auf Schadenhöhe / Reserve','Weiteres Vorgehen'],'zwischenbericht'=>['Aktueller Sachstand','Neue Erkenntnisse','Deckung / Ersatzpflicht','Schadenentwicklung','Beleg- / Nachtragsprüfung','Reserve','Zahlungen','Regress','Weiteres Vorgehen'],'schlussbericht'=>['Abschließender Sachstand','Schadenursache','Ersatzpflicht / Deckung','Finale Schadenermittlung','Zahlungen','Reserveabschluss','Regressergebnis','Abschlussbewertung'],'vorauszahlung'=>['Zahlungsempfänger','Betrag','Begründung','Deckungs- / Haftungsstand','Bisherige Zahlungen','Restreserve','Freigabe'],'query_form'=>['Offener Punkt','Sachverhalt','Bisherige Feststellungen','Konkrete Rückfrage','Benötigte Entscheidung / Unterlage'],default=>['Sachverhalt','Feststellungen','Bewertung','Empfehlung']};}
function gfDocumentHtml(string $key,array $meta,array $order,string $userName):string{$title=gfOutputTitle($key);$schaden=(string)($meta['schaden_nr']??'');$vsnr=(string)($meta['versicherungsschein_nr']??'');$obj=(string)($meta['vn_objekt']??'');$ort=trim(((string)($meta['strasse']??'')).' '.((string)($meta['ort']??'')));$reserve=(string)($meta['reserve']??'');$instruction=(string)($order['instructions']??'');$work=(string)($order['work_mode']??'');$open=(string)($order['open_points']??'');$sections='';foreach(gfSections($key)as$s)$sections.='<h2>'.gdH($s).'</h2><p><em>Aus der Fallakte fachlich zu befüllen. Fehlende Angaben als offen kennzeichnen; keine Tatsachen erfinden.</em></p>';$generated=date('d.m.Y H:i');return'<!doctype html><html><head><meta charset="utf-8"><title>'.gdH($title).'</title><style>body{font-family:Arial,sans-serif;font-size:11pt;line-height:1.45;margin:2cm;color:#111}h1{font-size:18pt;margin-bottom:18px}h2{font-size:13pt;margin-top:22px;border-bottom:1px solid #bbb;padding-bottom:4px}table{border-collapse:collapse;width:100%;margin:12px 0 20px}td{border:1px solid #ccc;padding:6px;vertical-align:top}.label{font-weight:bold;width:30%}.note{background:#f3f6f8;padding:10px;border:1px solid #d6e0e7}.footer{margin-top:30px}</style></head><body><h1>'.gdH($title).'</h1><table><tr><td class="label">Schaden-Nr.</td><td>'.gdH($schaden).'</td></tr><tr><td class="label">Versicherungsschein-Nr.</td><td>'.gdH($vsnr).'</td></tr><tr><td class="label">VN / Objekt</td><td>'.gdH($obj).'</td></tr><tr><td class="label">Schadenort</td><td>'.gdH($ort).'</td></tr><tr><td class="label">Aktuelle Schadenhöhe / Reserve</td><td>'.gdH($reserve).'</td></tr></table><div class="note"><strong>Arbeitsauftrag</strong><br>'.nl2br(gdH($instruction?:'Kein zusätzlicher Freitext hinterlegt.')).'<br><br><strong>Bearbeitungsart:</strong> '.gdH($work).'<br><strong>Offene Punkte:</strong> '.gdH($open).'</div>'.$sections.'<div class="footer"><p>Erstellt am '.gdH($generated).' durch '.gdH($userName).'.</p><p>Christian Wächter<br>Sachverständiger &amp; Großschadenregulierer<br>DIN EN ISO/IEC 17024 zertifiziert<br>https://www.sv-netzwerk.eu/</p></div></body></html>';}

switch($action){
case'status':gdAccessToken();gdEnsureKnownCasesRoots();$caseRoot=gdUserCasesRoot($user);$counts=['cases'=>count(gdListChildren($caseRoot['id'],null,1000)),'knowledge'=>count(gdListChildren(gdFolderId('knowledge'),null,1000)),'blanco'=>count(gdListChildren(gdFolderId('blanco'),null,1000))];apiJson(['ok'=>true,'connected'=>true,'user_scope'=>hash('sha256',gdUserKey($user)),'backoffice'=>$isBackoffice,'selected_expert'=>$selectedExpert,'folders'=>['cases'=>['id'=>$caseRoot['id'],'name'=>$caseRoot['name'],'items'=>$counts['cases']],'knowledge'=>['id'=>gdFolderId('knowledge'),'name'=>'00_KI-Wissensbasis','items'=>$counts['knowledge']],'blanco'=>['id'=>gdFolderId('blanco'),'name'=>'SV-GF Fälle','items'=>$counts['blanco']]]]);
case'recent_cases':
  $caseRoot=gdUserCasesRoot($user);
  $folders=gdListChildren($caseRoot['id'],'application/vnd.google-apps.folder',1000);
  usort($folders,static fn(array $a,array $b):int=>strcmp((string)($b['modifiedTime']??''),(string)($a['modifiedTime']??'')));
  $results=[];
  foreach(array_slice($folders,0,10)as$folder){
    try{$meta=gdCaseMeta((string)$folder['id']);}catch(Throwable){$meta=[];}
    $results[]=['id'=>$folder['id'],'name'=>$folder['name'],'modifiedTime'=>$folder['modifiedTime']??null,'webViewLink'=>$folder['webViewLink']??null,'meta'=>$meta];
  }
  apiJson(['ok'=>true,'results'=>$results]);
case'search_cases':$term=trim((string)($_GET['q']??''));$norm=gdNormalize($term);$caseRoot=gdUserCasesRoot($user);$folders=gdListChildren($caseRoot['id'],'application/vnd.google-apps.folder',1000);$results=[];foreach($folders as$folder){$name=(string)($folder['name']??'');$meta=[];$nameMatch=$norm===''||str_contains(gdNormalize($name),$norm);if(!$nameMatch||$norm===''){try{$meta=gdCaseMeta((string)$folder['id']);}catch(Throwable $e){$meta=[];}}$hay=gdNormalize($name.' '.implode(' ',array_map('strval',[$meta['schaden_nr']??'',$meta['vn_objekt']??'',$meta['ort']??'',$meta['strasse']??'',$meta['versicherungsschein_nr']??''])));if($norm!==''&&!str_contains($hay,$norm))continue;registerCaseFolderOwner((string)$folder['id'],$user,$meta);$results[]=['id'=>$folder['id'],'name'=>$name,'modifiedTime'=>$folder['modifiedTime']??null,'webViewLink'=>$folder['webViewLink']??null,'meta'=>$meta];if(count($results)>=100)break;}apiJson(['ok'=>true,'query'=>$term,'results'=>$results]);
case'load_case':$id=trim((string)($_GET['id']??''));gdAssertCaseAccess($id,$user);apiJson(['ok'=>true,'case'=>['id'=>$id,'meta'=>gdCaseMeta($id),'files'=>gdListChildren($id,null,1000)]]);
case'case_excel_forms':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');$body=requestBody();$folderId=trim((string)($body['folder_id']??''));gdAssertCaseAccess($folderId,$user);$forms=gdEnsureCaseExcelForms($folderId);foreach($forms as&$form)$form['webViewLink']='/intern/api/case-file-browser.php?action=file&folder_id='.rawurlencode($folderId).'&file_id='.rawurlencode((string)($form['id']??''));unset($form);apiJson(['ok'=>true,'files'=>$forms]);
case'save_case':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');$body=requestBody();$folderId=trim((string)($body['folder_id']??''));$data=is_array($body['case']??null)?$body['case']:[];$data['updated_at']=gmdate('c');$data['updated_by']=$user['full_name']??($user['email']??'');if($folderId===''){$root=gdUserCasesRoot($user);$folder=gdCreateFolder((string)$root['id'],gdCaseName($data));$folderId=(string)($folder['id']??'');if($folderId==='')apiError(503,'Fallordner konnte nicht angelegt werden.');$data['created_at']=$data['created_at']??gmdate('c');}else gdAssertCaseAccess($folderId,$user);registerCaseFolderOwner($folderId,$user,$data);gdUploadJson($folderId,CASE_META_NAME,$data);apiJson(['ok'=>true,'folder_id'=>$folderId,'name'=>gdCaseName($data)]);
case'upload_case_document':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');$folderId=trim((string)($_POST['folder_id']??''));gdAssertCaseAccess($folderId,$user);if(empty($_FILES['file']))apiError(400,'Keine Datei übergeben.');$f=$_FILES['file'];if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)apiError(400,'Datei konnte nicht hochgeladen werden.');$name=basename((string)($f['name']??'Unterlage'));$bytes=file_get_contents((string)$f['tmp_name']);if($bytes===false)apiError(400,'Datei konnte nicht gelesen werden.');$mime=mime_content_type((string)$f['tmp_name'])?:((string)($f['type']??'application/octet-stream'));$excludedReason=gdExcludedCaseAsset($name,$mime,$bytes);if($excludedReason!==null)apiJson(['ok'=>true,'excluded'=>true,'name'=>$name,'reason'=>$excludedReason,'file'=>null,'category'=>null,'duplicate'=>false]);$originalModified=max(0,(int)($_POST['last_modified']??0));$result=gdUploadCaseFile($folderId,$name,$mime,$bytes,$originalModified);apiJson(['ok'=>true,'excluded'=>false,'file'=>$result['file'],'name'=>$name,'category'=>$result['category'],'duplicate'=>$result['duplicate']]);
case'organize_case_documents':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');$body=requestBody();$folderId=trim((string)($body['folder_id']??''));gdAssertCaseAccess($folderId,$user);apiJson(['ok'=>true,'folder_id'=>$folderId]+gdOrganizeCase($folderId));
case'organize_all_cases':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');@set_time_limit(90);$body=requestBody();$offset=max(0,(int)($body['offset']??0));$limit=min(10,max(1,(int)($body['limit']??3)));$caseRoot=gdUserCasesRoot($user);$allCases=gdListChildren($caseRoot['id'],'application/vnd.google-apps.folder',1000);$cases=array_slice($allCases,$offset,$limit);$summary=['cases'=>0,'moved'=>0,'ignored'=>0,'errors'=>[]];foreach($cases as$case){$id=(string)($case['id']??'');if($id==='')continue;try{$result=gdOrganizeCase($id);$summary['cases']++;$summary['moved']+=$result['moved'];$summary['ignored']+=$result['ignored'];}catch(Throwable$e){$summary['errors'][]=['case'=>(string)($case['name']??$id),'error'=>$e->getMessage()];}}$next=$offset+count($cases);apiJson(['ok'=>count($summary['errors'])===0,'next_offset'=>$next,'done'=>$next>=count($allCases),'total'=>count($allCases)]+$summary);
case'generate_documents':if($_SERVER['REQUEST_METHOD']!=='POST')apiError(405,'POST erforderlich.');$body=requestBody();$folderId=trim((string)($body['folder_id']??''));$order=is_array($body['order']??null)?$body['order']:[];$outputs=array_values(array_filter(array_map('strval',is_array($order['outputs']??null)?$order['outputs']:[])));gdAssertCaseAccess($folderId,$user);if(!$outputs)apiError(400,'Keine Dokumente ausgewählt.');$allowed=['erstbericht','schadenprotokoll','schlusserklaerung','zahlungsbefuerwortung','nachtrag_stellungnahme','zwischenbericht','schlussbericht','vorauszahlung','query_form'];foreach($outputs as$o)if(!in_array($o,$allowed,true))apiError(400,'Unbekannter Dokumenttyp: '.$o);$meta=gdCaseMeta($folderId);if(!$meta)apiError(409,'Falldaten konnten nicht geladen werden.');$userName=(string)($user['full_name']??($user['email']??'Christian Wächter'));$stamp=date('Y-m-d_His');$casePart=gdSafeName((string)($meta['schaden_nr']??'Fall'));$created=[];foreach($outputs as$key){$title=gfOutputTitle($key);$name=$casePart.'_'.gdSafeName($title).'_'.$stamp.'.doc';$file=gdUploadBytes($folderId,$name,'application/msword',gfDocumentHtml($key,$meta,$order,$userName));$fileId=(string)($file['id']??'');$created[]=['id'=>$fileId,'name'=>$file['name']??$name,'webViewLink'=>'/intern/api/case-file-browser.php?action=file&folder_id='.rawurlencode($folderId).'&file_id='.rawurlencode($fileId),'webContentLink'=>null,'type'=>$key];}$order['generated_at']=gmdate('c');$order['generated_by']=$userName;$order['generated_files']=$created;gdUploadJson($folderId,'00_Dokumentauftrag_GF.json',$order);apiJson(['ok'=>true,'created'=>$created,'count'=>count($created)]);
case'sync_sources':$knowledge=gdListChildren(gdFolderId('knowledge'),null,1000);$blanco=gdListChildren(gdFolderId('blanco'),null,1000);$pick=function(array$items,array$needles):array{$out=[];foreach($items as$f){$n=gdNormalize((string)($f['name']??''));foreach($needles as$k=>$needle)if(str_contains($n,gdNormalize($needle))){$out[$k]=$f;break;}}return$out;};apiJson(['ok'=>true,'sources'=>['knowledge'=>$pick($knowledge,['master'=>'MASTER-ARBEITSSTANDARD','engel'=>'QS-Engel','gf_prompt'=>'Prompt GFGrossschaden','gf_richtlinien'=>'Zusammenfassung Richtlinien - SV GF-Schäden','erstbericht_anforderungen'=>'Groß TF SV Erstbericht Anforderungen Inhalt']),'blanco'=>$pick($blanco,['erstbericht'=>'Erstbericht','zwischenbericht'=>'Zwischenbericht','schlussbericht'=>'Schlussbericht','protokoll_gewerbe'=>'Schadenprotokoll_Gewerbe','protokoll_privat'=>'Schadenprotokoll_Privat','protokoll_frost'=>'Schadenprotokoll_Frost','schlusserklaerung_excel'=>'Schlusserklärung.xlsm','zahlungsbefuerwortung_excel'=>'Zahlungsbefürwortung.xlsm'])]]);
default:apiError(400,'Unbekannte Aktion.');}
