<?php
declare(strict_types=1);

function trCp(string $text): string { $value=@iconv('UTF-8','Windows-1252//TRANSLIT',$text); return $value===false?(preg_replace('/[^\x20-\x7E]/','?',$text)??''):$value; }
function trEsc(string $text): string { return str_replace(['\\','(',')',"\r"],['\\\\','\\(','\\)',''],trCp($text)); }
function trMoney(mixed $value): string { return is_numeric($value)?number_format((float)$value,2,',','.').' EUR':'-'; }
function trNumber(mixed $value): string { return is_numeric($value)?number_format((float)$value,abs((float)$value-round((float)$value))<.0001?0:2,',','.'):'-'; }
function trDate(string $value): string { foreach(['Y-m-d','d.m.Y','j. F Y'] as $format){$date=DateTimeImmutable::createFromFormat($format,$value);if($date)return$date->format('d.m.Y');}return$value!==''?$value:'-'; }
function trWrap(string $text,int $max=82): array { $text=trim(preg_replace('/\s+/u',' ',$text)??'');if($text==='')return['-'];$out=[];$line='';foreach(preg_split('/\s+/u',$text)?:[]as$word){$test=$line===''?$word:$line.' '.$word;if(mb_strlen($test,'UTF-8')>$max&&$line!==''){$out[]=$line;$line=$word;}else{$line=$test;}}if($line!=='')$out[]=$line;return$out; }
function trText(array &$ops,float $x,float $y,string $text,float $size=9,bool $bold=false,array $color=[0,0,0]): void { $ops[]=sprintf('BT /%s %.2F Tf %.3F %.3F %.3F rg %.2F %.2F Td (%s) Tj ET',$bold?'F2':'F1',$size,$color[0],$color[1],$color[2],$x,$y,trEsc($text)); }
function trRight(array &$ops,float $right,float $y,string $text,float $size=9,bool $bold=false,array $color=[0,0,0]): void { $width=strlen(trCp($text))*$size*.49;trText($ops,max(42,$right-$width),$y,$text,$size,$bold,$color); }
function trFill(array &$ops,float $x,float $y,float $width,float $height,array $color): void { $ops[]=sprintf('%.3F %.3F %.3F rg %.2F %.2F %.2F %.2F re f',$color[0],$color[1],$color[2],$x,$y,$width,$height); }
function trLine(array &$ops,float $x1,float $y1,float $x2,float $y2,array $color,float $width=.5): void { $ops[]=sprintf('%.2F w %.3F %.3F %.3F RG %.2F %.2F m %.2F %.2F l S',$width,$color[0],$color[1],$color[2],$x1,$y1,$x2,$y2); }
function trHeader(array &$ops,bool $continuation=false): float { $navy=[.027,.102,.180];$orange=[1,.616,.071];$muted=[.35,.443,.522];$line=[.82,.867,.902];trText($ops,45,793,'SV',26,true,$orange);trText($ops,88,799,'sv-netzwerk.eu',15,true,$navy);trText($ops,89,787,'BAU - SCHADEN - REGULIERUNG',6.5,true,$muted);trRight($ops,550,799,'TECHNISCHE KVA-FREIGABE',8,true,$navy);if($continuation)trRight($ops,550,787,'Fortsetzung',7,false,$muted);trLine($ops,45,775,550,775,$line,.7);trFill($ops,45,771,72,3,$orange);return 752; }
function trStart(array &$pages,array &$ops,float &$y): void { if($ops)$pages[]=$ops;$ops=[];$y=trHeader($ops,count($pages)>0); }
function trNeed(array &$pages,array &$ops,float &$y,float $height): void { if($y-$height<66)trStart($pages,$ops,$y); }
function trParagraph(array &$pages,array &$ops,float &$y,string $text,int $max=94,float $size=8.5,bool $bold=false): void { $navy=[.027,.102,.180];foreach(trWrap($text,$max)as$line){trNeed($pages,$ops,$y,$size+5);trText($ops,50,$y,$line,$size,$bold,$navy);$y-=$size+4;}$y-=4; }
function trField(array &$ops,float $x,float $y,string $label,string $value,float $valueX=0): void { $navy=[.027,.102,.180];$muted=[.35,.443,.522];trText($ops,$x,$y,$label,6.7,true,$muted);trText($ops,$valueX>0?$valueX:$x,$y-14,$value!==''?$value:'-',8.5,true,$navy); }
function trDetailHeader(array &$ops,float &$y): void { $navy=[.027,.102,.180];$panel=[.956,.972,.984];trFill($ops,45,$y-20,505,20,$panel);trText($ops,50,$y-13,'Pos.',7,true,$navy);trText($ops,82,$y-13,'Leistung',7,true,$navy);trText($ops,365,$y-13,'Menge',7,true,$navy);trRight($ops,470,$y-13,'Einzel netto',7,true,$navy);trRight($ops,545,$y-13,'Gesamt netto',7,true,$navy);$y-=23; }

function trBuildTechnicalReleasePdf(array $data): string
{
    $quotes=is_array($data['quotes']??null)?array_values($data['quotes']):[];
    if($quotes===[])throw new RuntimeException('Keine geprüften Kostenvoranschläge vorhanden.');
    $meta=is_array($data['meta']??null)?$data['meta']:[];
    $navy=[.027,.102,.180];$orange=[1,.616,.071];$muted=[.35,.443,.522];$line=[.82,.867,.902];$panel=[.956,.972,.984];$green=[.90,.96,.92];$warn=[1,.95,.89];
    $pages=[];$ops=[];$y=0.0;trStart($pages,$ops,$y);
    trText($ops,45,$y,'Technische Freigabe',19,true,$navy);$y-=18;trText($ops,45,$y,'Prüfung und Freigabe der eingereichten Kostenvoranschläge',9,false,$muted);$y-=24;
    trFill($ops,45,$y-112,505,112,$panel);trFill($ops,45,$y-112,4,112,$orange);
    trField($ops,60,$y-17,'SCHADEN-NR.',trim((string)($meta['case_no']??'')));trField($ops,410,$y-17,'DATUM',trDate(trim((string)($meta['date']??date('Y-m-d')))));
    trField($ops,60,$y-50,'VERSICHERUNGSNEHMER / OBJEKT',trim((string)($meta['vn']??'')));trField($ops,330,$y-50,'VERSICHERER',trim((string)($meta['insurer']??'')));
    trField($ops,60,$y-83,'SCHADENORT',trim((string)($meta['location']??'')));trField($ops,330,$y-83,'GEPRÜFT DURCH',trim((string)($meta['regulator']??'')));
    $y-=132;trText($ops,45,$y,'Prüfungsergebnis',13,true,$navy);$y-=9;trFill($ops,45,$y-2,46,3,$orange);$y-=18;
    $decision=trim((string)($meta['decision']??'Freigabe mit Vorbehalt'));$boxColor=preg_match('/rückfrage|ablehnung/i',$decision)?$warn:$green;trFill($ops,45,$y-42,505,42,$boxColor);trText($ops,60,$y-17,'ENTSCHEIDUNG',6.7,true,$muted);trText($ops,60,$y-33,$decision,11,true,$navy);$y-=58;
    trParagraph($pages,$ops,$y,trim((string)($meta['assessment']??'Die eingereichten Leistungen und Beträge wurden technisch und rechnerisch geprüft.')),94,8.5,false);
    trNeed($pages,$ops,$y,65);trText($ops,45,$y,'Kostenübersicht',13,true,$navy);$y-=10;trFill($ops,45,$y-2,46,3,$orange);$y-=16;
    trFill($ops,45,$y-22,505,22,$navy);trText($ops,51,$y-15,'KVA / Angebot',7.3,true,[1,1,1]);trText($ops,156,$y-15,'Anbieter',7.3,true,[1,1,1]);trRight($ops,405,$y-15,'Netto',7.3,true,[1,1,1]);trRight($ops,485,$y-15,'Brutto',7.3,true,[1,1,1]);trText($ops,495,$y-15,'Status',7.3,true,[1,1,1]);$y-=22;
    $totalNet=0.0;$totalGross=0.0;
    foreach($quotes as$index=>$quote){$height=34;trNeed($pages,$ops,$y,$height+24);if($index%2===1)trFill($ops,45,$y-$height,505,$height,[.985,.990,.994]);$number=trim((string)($quote['quote_number']??''));$company=trim((string)($quote['company']??''));trText($ops,51,$y-15,$number!==''?$number:'ohne Nummer',8,true,$navy);trText($ops,156,$y-15,$company!==''?$company:'nicht erkannt',8,false,$navy);trRight($ops,405,$y-15,trMoney($quote['net_total']??null),8,true,$navy);trRight($ops,485,$y-15,trMoney($quote['gross_total']??null),8,true,$navy);trText($ops,495,$y-15,trim((string)($quote['status']??$decision)),6.8,false,$navy);trLine($ops,45,$y-$height,550,$y-$height,$line,.35);$y-=$height;if(is_numeric($quote['net_total']??null))$totalNet+=(float)$quote['net_total'];if(is_numeric($quote['gross_total']??null))$totalGross+=(float)$quote['gross_total'];}
    trNeed($pages,$ops,$y,72);trFill($ops,45,$y-58,505,58,$green);trFill($ops,45,$y-58,4,58,$orange);trText($ops,60,$y-18,'GESAMTFREIGABE',7,true,$muted);trText($ops,60,$y-39,'Gesamtsumme netto',9,true,$navy);trRight($ops,350,$y-39,trMoney($totalNet),11,true,$navy);trText($ops,370,$y-39,'Gesamtsumme brutto',9,true,$navy);trRight($ops,535,$y-39,trMoney($totalGross),11,true,$navy);$y-=78;
    trText($ops,45,$y,'Abgrenzung und Hinweise',13,true,$navy);$y-=10;trFill($ops,45,$y-2,46,3,$orange);$y-=18;trParagraph($pages,$ops,$y,trim((string)($meta['delimitation']??'Die Freigabe umfasst ausschließlich die beschriebenen und geprüften Leistungen. Zusatz- oder Mehrkosten sind vor Ausführung gesondert abzustimmen.')),94,8.5,false);

    foreach($quotes as$quoteIndex=>$quote){trStart($pages,$ops,$y);$title='KVA '.($quoteIndex+1).' - '.trim((string)($quote['company']??'Anbieter'));trText($ops,45,$y,$title,17,true,$navy);$y-=24;trFill($ops,45,$y-68,505,68,$panel);trFill($ops,45,$y-68,4,68,$orange);trField($ops,60,$y-17,'ANGEBOTS-NR.',trim((string)($quote['quote_number']??'')));trField($ops,220,$y-17,'ANGEBOTSDATUM',trDate(trim((string)($quote['quote_date']??''))));trField($ops,390,$y-17,'QUELLE',trim((string)($quote['source']??'')));trField($ops,60,$y-49,'ANBIETER',trim((string)($quote['company']??'')));$y-=88;
        trDetailHeader($ops,$y);$positions=is_array($quote['positions']??null)?$quote['positions']:[];
        foreach($positions as$index=>$position){$description=trWrap(trim((string)($position['description']??'')),50);$height=max(30,14+count($description)*9);if($y-$height<70){trStart($pages,$ops,$y);trText($ops,45,$y,$title.' - Fortsetzung',14,true,$navy);$y-=24;trDetailHeader($ops,$y);}if($index%2===1)trFill($ops,45,$y-$height,505,$height,[.985,.990,.994]);trText($ops,51,$y-14,trim((string)($position['position_no']??($index+1))),7.5,true,$navy);foreach($description as$lineIndex=>$value)trText($ops,82,$y-14-$lineIndex*9,$value,7.2,false,$navy);$quantity=trNumber($position['quantity']??null).' '.trim((string)($position['unit']??''));trText($ops,365,$y-14,$quantity,7.2,false,$navy);trRight($ops,470,$y-14,trMoney($position['unit_price']??null),7.2,false,$navy);trRight($ops,545,$y-14,trMoney($position['line_total']??null),7.4,true,$navy);trLine($ops,45,$y-$height,550,$y-$height,$line,.3);$y-=$height;}
        trNeed($pages,$ops,$y,96);$y-=12;trFill($ops,300,$y-70,250,70,$panel);trText($ops,315,$y-17,'Netto',8,false,$navy);trRight($ops,535,$y-17,trMoney($quote['net_total']??null),9,true,$navy);$vatLabel='Umsatzsteuer '.trNumber($quote['vat_rate']??null).' %';trText($ops,315,$y-37,$vatLabel,8,false,$navy);trRight($ops,535,$y-37,trMoney($quote['vat_total']??null),9,true,$navy);trText($ops,315,$y-57,'Brutto',8,true,$navy);trRight($ops,535,$y-57,trMoney($quote['gross_total']??null),10,true,$navy);$y-=90;
        trText($ops,45,$y,'Technische Bewertung',12,true,$navy);$y-=18;trParagraph($pages,$ops,$y,trim((string)($quote['technical_assessment']??'Die angebotenen Positionen wurden auf technische Plausibilität und rechnerische Nachvollziehbarkeit geprüft.')),94,8.2,false);trText($ops,45,$y,'Freigabeumfang',12,true,$navy);$y-=18;trParagraph($pages,$ops,$y,trim((string)($quote['release_scope']??$meta['delimitation']??'')),94,8.2,false);
    }
    trNeed($pages,$ops,$y,70);$y-=20;trLine($ops,350,$y,545,$y,[.09,.196,.286],.8);$y-=15;trText($ops,350,$y,trim((string)($meta['regulator']??'')),9,true,$navy);$y-=12;trText($ops,350,$y,'Sachverständiger & Schadenregulierer',7.5,false,$muted);if($ops)$pages[]=$ops;
    $count=count($pages);foreach($pages as$index=>&$page){trLine($page,45,45,550,45,$line,.5);trText($page,45,31,'SV-Netzwerk Prüfportal',6.5,false,$muted);trRight($page,550,31,'Seite '.($index+1).' von '.$count,6.5,false,$muted);}unset($page);
    $objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>'];$pageStart=5;$contentStart=$pageStart+$count;$kids=[];for($i=0;$i<$count;$i++)$kids[]=($pageStart+$i).' 0 R';$objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.$count.' >>';$objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';$objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';foreach($pages as$i=>$page){$objects[$pageStart+$i]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents '.($contentStart+$i).' 0 R >>';$stream=implode("\n",$page);$objects[$contentStart+$i]="<< /Length ".strlen($stream).">>\nstream\n$stream\nendstream";}ksort($objects);$pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$offsets=[0];foreach($objects as$number=>$object){$offsets[$number]=strlen($pdf);$pdf.="$number 0 obj\n$object\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$offsets[$i]??0)."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";return$pdf;
}
