<?php
declare(strict_types=1);
require_once __DIR__.'/../public/intern/api/bki-batch.php';
require_once __DIR__.'/../public/intern/api/bki-catalog-calculation.php';
$component=['description'=>'Gussrohrleitung demontieren, bis DN100','scope'=>'Durchmesser: DN50 bis DN100','source_quote'=>'Gussrohrleitung'];
$row=['description'=>'Rückbau alte Gussfallleitung','scope'=>'12 m, alte Befestigungen entfernen'];
if(bkCatalogScopeIssue($component,$row,[])==='')throw new RuntimeException('Unbekannter Alt-DN wurde angenommen.');
if(bkCatalogScopeIssue($component,$row,['notes'=>'Planungsannahme Gussleitung DN150'])==='')throw new RuntimeException('Falsche DN-Variante angenommen.');
$component['scope']='Durchmesser: DN125 bis DN200';$component['description']='Gussrohrleitung demontieren, bis DN200';
if(bkCatalogScopeIssue($component,$row,['notes'=>'Planungsannahme Gussleitung DN150'])!=='')throw new RuntimeException('Belegte Planungsvariante fehlt.');
echo "Old-pipe dimensions remain separate from replacement dimensions.\n";
$parts=[['id'=>'packet','source_action'=>'Herstellen','gross_prices'=>[85,92,109],'quantity_verified'=>true,'scope_issue'=>'','unit'=>'m','quantity'=>12,'description'=>'Abwasser HT-Rohrleitungen DN/OD110 Formteile','position_code'=>'411.10/05'],['id'=>'pipe','quantity_verified'=>true,'scope_issue'=>'','unit'=>'m','quantity'=>12,'description'=>'Abwasserleitung HT-Rohr DN/OD110']];
$parts=bkCatalogRemoveOverlap($parts);if($parts[1]['scope_issue']==='')throw new RuntimeException('Paket und Einzelrohr wurden doppelt angesetzt.');
echo "Assembly prices exclude duplicate constituent pipe prices.\n";
$queries=bkCatalogQueries(['description'=>'Abfallentsorgung und Baustellenreinigung','scope'=>'mineralischen Bauschutt getrennt entsorgen']);
if(!in_array('Bauschutt entsorgen',$queries,true)||!in_array('Baureinigung Baubetrieb',$queries,true))throw new RuntimeException('KVA-Synonyme erreichen die vorhandenen Originalpreise nicht.');
$queries=bkCatalogQueries(['description'=>'Kontrolliertes Öffnen des Installationsbereichs','scope'=>'Mauerwerk entlang der Fallleitung öffnen']);
if(!in_array('Schlitz Mauerwerk',$queries,true))throw new RuntimeException('Wandschlitz fehlt in den Suchvarianten.');
echo "Offer vocabulary reaches original work-item terminology.\n";
$shared=['id'=>'shared','scope'=>'Original scope','unit'=>'m'];
$request=bkCatalogPromptInput([], [['row_id'=>'0','candidates'=>[$shared]],['row_id'=>'1','candidates'=>[$shared]]], [], 'Kuchen');
if(count($request['original_catalog'])!==1||count($request['candidate_groups'])!==2||$request['candidate_groups'][1]['candidate_ids']!==['shared']||$request['original_catalog'][0]['scope']!=='Original scope')throw new RuntimeException('Shared source text was duplicated or lost.');
echo "Shared original evidence is sent once without losing row assignments.\n";
$pp=['id'=>'pp','document_id'=>'book','source_action'=>'Herstellen','unit'=>'m','description'=>'Abwasser PP-Rohrleitungen DN/OD110 gedämmt','price_mid'=>124];
$ht=['id'=>'ht','document_id'=>'book','source_action'=>'Herstellen','unit'=>'m','description'=>'Abwasser HT-Rohrleitungen DN/OD110 gedämmt','price_mid'=>77];
$row=['description'=>'Neue HT-Fallleitung','scope'=>'PP DN/OD110'];
if(bkCatalogSystemPosition($pp,$row,[$pp,$ht])['id']!=='ht')throw new RuntimeException('Broad polymer designation displaced specified HT system.');
$row['description']='Neue PP-Fallleitung';
if(bkCatalogSystemPosition($pp,$row,[$pp,$ht])['id']!=='pp')throw new RuntimeException('Unrequested pipe system was substituted.');
echo "Specified pipe systems retain their own original price.\n";
