import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/intern/claimsforce-central.js',import.meta.url),'utf8');
const start=source.indexOf('  const importControlState=');
const end=source.indexOf('  const refreshControl=',start);
const state=vm.runInNewContext(source.slice(start,end)+'importControlState;');
const single={id:10,profile:'christian',sync_mode:'single',claim_number:'26-085905-9',status:'running'};
assert.equal(state([single],'christian').action,'pause');
assert.equal(state([{...single,status:'failed'}],'christian').action,'resume');
assert.equal(state([{...single,status:'done'}],'christian').action,'recheck');
assert.equal(state([{...single,profile:'marc'}],'christian').action,'idle');
assert.equal(state([{...single,status:'failed'},{...single,id:11,status:'queued'}],'christian').job.id,11);
const stopped={...single,status:'failed'};
const selected=state([stopped,{id:12,profile:'marc',status:'running'}],'christian');
assert.equal(selected.job.claim_number,'26-085905-9');
assert.equal(selected.job.sync_mode,'single');
// Die echte Enqueue-Funktion darf beim Fortsetzen keine geänderte Eingabe übernehmen.
const enqueue=source.slice(source.indexOf('  const enqueue=async'),source.indexOf('  window.svnetClaimsTaskCheck='));
const queued=[];const claimInput={value:'26-076821-6',disabled:false};
const sandbox={userJobs:[],context:{claims_agent:true},bridge:true,button:{},fullButton:{},claimInput,controlJobs:[],selectedProfile:()=> 'christian',show:()=>{},refreshControl:()=>{},watch:()=>{},post:async(action,payload)=>{queued.push({action,payload});return {job:{id:20,profile:payload.profile,sync_mode:payload.mode,claim_number:payload.claimNumber}};}};
await vm.runInNewContext(enqueue+'enqueue;',sandbox)('single','christian',stopped);
assert.equal(queued[0].payload.claimNumber,'26-085905-9');
assert.equal(queued[0].payload.mode,'single');
assert.equal(claimInput.value,'26-085905-9');
queued.length=0;sandbox.userJobs=[];
await vm.runInNewContext(enqueue+'enqueue;',{...sandbox,userJobs:[]})('full','christian',{...stopped,sync_mode:'full',since_date:'2026-01-01'});
assert.equal(queued[0].payload.mode,'full');
assert.equal(queued[0].payload.since,'2026-01-01');
console.log('Pause/Fortsetzen/erneut prüfen, Profiltrennung und unveränderter Einzelumfang geprüft.');
