<?php
declare(strict_types=1);
require_once __DIR__.'/../public/intern/api/gf-saved-calculation.php';
$assert=static function(bool$condition,string$message):void{if(!$condition)throw new RuntimeException($message);};
$assert(gfInstructionUsesSavedCalculation('Auf Grund der Kalkulation Schlusserklärung erstellen.'),'Der konkrete Arbeitsauftrag muss die gespeicherte Kalkulation aktivieren.');
$assert(gfInstructionUsesSavedCalculation('Schlusserklärung anhand der Kalkulation erstellen.'),'Alternative eindeutige Formulierung wurde nicht erkannt.');
$assert(!gfInstructionUsesSavedCalculation('Schlusserklärung aus den Rechnungen erstellen.'),'Eine Schlusserklärung ohne Kalkulationsauftrag darf nicht auf die Kalkulation umgestellt werden.');
$row=['id'=>21,'created_at'=>'2026-09-01 15:04:14','vat_rate'=>'19.00','vat_total'=>'784.42','items_json'=>json_encode([['position_code'=>'01.01.000','description'=>'Ortung / Reparatur: Ergebnisorientierte Leckageortungspauschale inklusive Kosten für den Einsatz aller gängigen','quantity'=>1,'unit'=>'psch','unit_price'=>350,'regional_factor'=>1],['position_code'=>'13.05.004','description'=>'Wiederherstellung Laminat: Laminatboden liefern und verlegen inkl. Material','quantity'=>24,'unit'=>'m²','unit_price'=>50,'regional_factor'=>1],['type'=>'section','description'=>'Wiederherstellung'],['position_code'=>'LEER','description'=>'','quantity'=>1,'unit'=>'St','unit_price'=>0,'regional_factor'=>1]],JSON_UNESCAPED_UNICODE)];
$entries=gfSavedCalculationEntriesFromRow($row);$assert(count($entries)===3,'Zwei belastbare Positionen plus Umsatzsteuer wurden erwartet.');$assert($entries[0]['amount']===350.0,'Leckageortung wurde nicht korrekt berechnet.');$assert($entries[1]['amount']===1200.0,'Laminatposition wurde nicht korrekt berechnet.');$assert($entries[2]['amount']===784.42,'Umsatzsteuer wurde nicht übernommen.');$assert(array_sum(array_column($entries,'amount'))===2334.42,'Bruttosumme der Testpositionen ist falsch.');$assert($entries[1]['source_type']==='Kalkulation'&&str_contains($entries[1]['source_reference'],'21'),'Kalkulationsquelle fehlt.');
$assert($entries[0]['description']==='Leckageortungspauschale','Die Schlusserklärung darf keinen langen BKI-Katalogtext für die Leckageortung enthalten.');
$assert($entries[1]['description']==='Laminat liefern und verlegen','Die Laminatposition wurde nicht lesbar gekürzt.');
$assert(!str_contains($entries[0]['description'],'01.01.000')&&!str_contains($entries[0]['description'],'1 psch'),'Positionscode und Menge gehören nicht in die Kurzbezeichnung.');
$generator=file_get_contents(__DIR__.'/../public/intern/api/gf-ai-generate.php');$core=file_get_contents(__DIR__.'/../public/intern/api/gf-ai-generate-core.php');$assert(is_string($generator)&&str_contains($generator,'gfApplySavedCalculationToSchlusserklaerung($key,$result,$folderId,$instructions)'),'Gespeicherte Kalkulation ist nicht an die Dokumenterstellung angebunden.');$assert(is_string($core)&&str_contains($core,"'approved_saved_calculation_gate'"),'Excel-QS kennt die ausdrücklich beauftragte Kalkulationsgrundlage nicht.');$assert(str_contains($core,"==='kalkulation'?trim((string)(\$entry['description']??''))"),'Kalkulationszeilen der Schlusserklärung dürfen Quelle, Nummer und Datum nicht voranstellen.');echo "gf_saved_calculation_test: ok\n";
