import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync(new URL('../src/pages/intern/telefon/index.astro', import.meta.url), 'utf8');
const api = readFileSync(new URL('../public/intern/api/phonebook.php', import.meta.url), 'utf8');

assert(page.includes('Telefonbuch pflegen und Kontakte importieren'), 'Telefonbuchpflege fehlt.');
assert(page.includes('ph-setup-compact') && !page.includes('Einmalige Windows-Einrichtung für Annehmen und Auflegen</summary>'), 'Windows-Einrichtung muss platzsparend im Wählbereich stehen.');
assert(page.includes('accept=".csv,.vcf'), 'CSV- und VCF-Import fehlt.');
assert(page.includes('ph-contact-replace') && page.includes('action=replace') && page.includes('confirm_replace:true'), 'Atomarer Portalabgleich fehlt.');
assert(page.includes('Apple/iCloud') && page.includes('chunkSize=500'), 'Apple-Hinweis oder stapelweiser Großimport fehlt.');
assert(page.includes("PHONEBOOK_API='/intern/api/phonebook.php'"), 'Telefonbuch-API ist nicht angebunden.');
assert(page.includes("action=save") && page.includes("action=delete") && page.includes("action=import"), 'Pflegeaktionen sind unvollständig.');
assert(page.includes('ph-clean-unwanted') && page.includes('action=cleanup_unwanted'), 'Gezielte Bereinigung für Andersson, AB und per Mail fehlt.');
assert(page.includes('Alle markieren') && page.includes('Auswahl löschen') && page.includes('action=delete_many'), 'Mehrfachauswahl im Telefonbuch fehlt.');
assert(page.includes('Doppelte Rufnummern bereinigen') && page.includes('action=cleanup_duplicates'), 'Dublettenbereinigung fehlt.');
assert(page.includes('Gleiche Namen / Durchwahlen prüfen') && page.includes('action=same_name_review'), 'Manuelle Prüfliste für unterschiedliche Durchwahlen fehlt.');
assert(page.includes("addToSpeedDial"), 'Übernahme in die persönliche Kurzwahl fehlt.');
assert(page.includes('Promise.allSettled'), 'Telefonbuch- und Fallsuche müssen bei einem Teilfehler getrennt weiterlaufen.');
assert(page.includes('per_page=100') && page.includes('Seite ${page} von ${pages}') && page.includes("actionButton('Weiter'"), 'Vollständige paginierte Telefonbuchanzeige fehlt.');
assert(api.includes("'total' => $total") && api.includes("'pages' => $pages") && api.includes('array_slice($allContacts, $offset, $perPage)'), 'Serverseitige Telefonbuch-Paginierung fehlt.');
assert(api.includes('int $groupLimit = 0'), 'Die feste 500er-Anzeigegrenze muss entfernt sein.');
assert(api.includes('CREATE TABLE IF NOT EXISTS phonebook_contacts'), 'Zentrale Telefonbuchtabelle fehlt.');
assert(api.includes("WHERE phone_key=:phone_key AND name=:name ORDER BY id LIMIT 1"), 'Import muss Rufnummern desselben Kontakts zusammenführen, ohne andere Namen zu verlieren.');
assert(api.includes("$action === 'list'") && api.includes("$action === 'save'") && api.includes("$action === 'delete'") && api.includes("$action === 'import'"), 'API-Aktionen sind unvollständig.');
assert(api.includes("$action === 'cleanup_unwanted'") && api.includes("andersson|\\bab\\b|per\\s*mail"), 'Serverseitige Schrottkontakt-Bereinigung fehlt.');
assert(api.includes("$action === 'delete_many'") && api.includes('count($ids) > 500'), 'Begrenzte Sammellöschung fehlt.');
assert(api.includes("$action === 'replace'") && api.includes("$pdo->exec('DELETE FROM phonebook_contacts')") && api.includes('$pdo->beginTransaction()'), 'Transaktionaler Portalabgleich fehlt.');
assert(api.includes("$action === 'cleanup_duplicates'") && api.includes('phonebookPhoneKey'), 'Serverseitige Dublettenbereinigung fehlt.');
assert(api.includes("$action === 'same_name_review'") && api.includes("count($contact['phones'] ?? []) > 1"), 'API-Prüfliste für gleiche Namen mit unterschiedlichen Nummern fehlt.');
assert(page.includes('ph-contact-business') && page.includes('ph-contact-private') && page.includes('ph-contact-mobile') && page.includes('ph-contact-email'), 'Strukturierte Kontaktfelder fehlen.');
assert(page.includes('ph-contact-details') && page.includes('<details'), 'Mehrere Nummern müssen pro Kontakt aufklappbar sein.');
assert(api.includes("$action === 'save_group'") && api.includes('phonebookTypedPhones'), 'Gebündeltes Speichern eines Kontakts fehlt.');
assert(page.includes('ph-create-contact') && page.includes('createContactFromSearch'), 'Direktes Anlegen aus einer erfolglosen Suche fehlt.');
console.log('phonebook_page_test: ok');
