import fs from 'node:fs';
const fromProject=path=>new URL(`../${path}`,import.meta.url);
const page=fs.readFileSync(fromProject('src/pages/intern/versicherungsfaelle/index.astro'),'utf8');
const api=fs.readFileSync(fromProject('public/intern/api/whatsapp-case.php'),'utf8');
const client=fs.readFileSync(fromProject('public/intern/whatsapp-case.js'),'utf8');
const accountPage=fs.readFileSync(fromProject('src/pages/intern/whatsapp/index.astro'),'utf8');
const accountClient=fs.readFileSync(fromProject('public/intern/whatsapp-account.js'),'utf8');
const templateApi=fs.readFileSync(fromProject('public/intern/api/whatsapp-template-send.php'),'utf8');
const layout=fs.readFileSync(fromProject('src/layouts/InternalLayout.astro'),'utf8');
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
for(const token of ['vf-wa-panel','vf-wa-vn','vf-wa-sanierer','vf-wa-send','vf-wa-connect','WhatsApp verbinden','WhatsApp noch nicht verbunden','/intern/whatsapp-case.js'])assert(page.includes(token),`Portalbestandteil fehlt: ${token}`);
assert(!api.includes("'susanne' =>")&&!api.includes("'jens' =>"),'Susanne und Jens dürfen kein WhatsApp-Profil erhalten');
for(const token of ['christian','holger','marc','WHATSAPP_CHRISTIAN_PHONE_NUMBER_ID','WHATSAPP_HOLGER_PHONE_NUMBER_ID','WHATSAPP_MARC_PHONE_NUMBER_ID','WHATSAPP_MARC_WABA_ID','WHATSAPP_MARC_ACCESS_TOKEN'])assert(api.includes(token),`Profilkonfiguration fehlt: ${token}`);
for(const number of ['+4973673103045','+491731645162','+4923926592751'])assert(api.includes(`'number'=>'${number}'`),`WhatsApp-Business-Nummer fehlt: ${number}`);
assert(!api.includes("'number'=>'+491604092134'"),'Christians frühere Mobilnummer darf nicht mehr als WhatsApp-Business-Nummer verwendet werden');
assert(api.includes("'1282747221593843'")&&api.includes("'2484676038720950'"),'Christians neue Meta-Telefon- und WABA-Zuordnung muss im Portal vorbereitet sein');
assert(!api.includes('+491712119777'),'Marcs frühere Mobilnummer darf nicht mehr als WhatsApp-Business-Nummer verwendet werden');
assert(api.includes("'access_token'=>waEnv('WHATSAPP_MARC_ACCESS_TOKEN')")&&api.includes("'access_token'=>waEnv('WHATSAPP_HOLGER_ACCESS_TOKEN')")&&api.includes("'access_token'=>waEnv('WHATSAPP_CHRISTIAN_ACCESS_TOKEN',waEnv('WHATSAPP_ACCESS_TOKEN'))"),'Der globale Übergangstoken darf nicht auf Marcs oder Holgers WhatsApp-Konto übergreifen');
assert(api.includes('Portal-App noch nicht mit Meta verbunden'),'Ein fehlendes Portal-App-Setup darf nicht als fehlende WhatsApp-Business-Registrierung dargestellt werden');
assert(api.includes('$pendingReview = false')&&api.includes("'pending_review'=>\$pendingReview")&&client.includes("connect.disabled=!connection.onboarding_available||connection.connected")&&client.includes("connection.onboarding_available?'WhatsApp verbinden'"),'Eine vorbereitete Meta-Nummer darf Embedded Signup nicht blockieren');
assert(api.includes("$metaBusinessApproved = $profileKey === 'christian'")&&api.includes("$metaCoexistenceConnected = $profileKey === 'christian'")&&api.includes("'meta_account_status'=>\$metaBusinessApproved?'APPROVED':'UNKNOWN'")&&api.includes("'meta_coexistence_connected'=>\$metaCoexistenceConnected")&&api.includes('Meta-Konto und Coexistence verbunden · Portalzugriff wird geprüft'),'Christians genehmigtes Meta-Unternehmenskonto und die bestehende Coexistence-Verbindung müssen getrennt von der technischen Versandbereitschaft ausgewiesen werden');
for(const token of ['whatsapp_profile_connections','WHATSAPP_META_APP_ID','WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID','waEncryptToken','is_on_biz_app','complete_signup','subscribed_apps'])assert(api.includes(token),`Sichere Meta-Selbstverbindung fehlt: ${token}`);
for(const token of ['X_HUB_SIGNATURE_256',"hash_hmac('sha256'",'last_outbound_wamid','valid_until>=NOW()','unassigned','gd'])void token;
assert(api.includes('HTTP_X_HUB_SIGNATURE_256')&&api.includes("hash_hmac('sha256'"),'Webhook-Signaturprüfung fehlt');
assert(api.includes('last_outbound_wamid')&&api.includes('valid_until>=NOW()'),'Kontextgebundene Fallzuordnung fehlt');
assert(api.includes("status'=>'unassigned'")||api.includes("'unassigned'"),'Nicht eindeutige Eingänge müssen unzugeordnet bleiben');
assert(api.includes("$action === 'assign_message'")&&client.includes('Aktivem Fall zuordnen'),'Manuelle Zuordnung eines uneindeutigen WhatsApp-Eingangs fehlt');
assert(api.includes("'02_Fotos'")&&api.includes("'04_Rechnungen_KVA'")&&api.includes("'07_Korrespondenz'"),'Drive-Zielordner fehlen');
assert(client.includes('meta.mobil')&&client.includes('meta.telefon')&&client.includes('meta.sanierer_mobil')&&client.includes('meta.sanierer_telefon'),'VN- und Sanierer-Rufnummern werden nicht getrennt übernommen');
assert(client.includes('telefonkontakte')&&client.includes('addCasePhonePicker')&&client.includes('Aus Akte übernehmen'),'VN-, Sanierer- und zusätzliche Aktenkontakte müssen in der WhatsApp-Terminierung auswählbar sein');
assert(client.includes('connection?.connected'),'Versand darf ohne Meta-Verbindung nicht aktiv werden');
assert(client.includes('whatsapp_business_app_onboarding')&&client.includes('WA_EMBEDDED_SIGNUP'),'Meta-Coexistence muss aus dem Portal geführt werden');
assert(client.includes('Die WhatsApp-Konten anderer Bearbeiter bleiben getrennt.'),'Der Verbindungsdialog muss die profilbezogene Kontentrennung eindeutig anzeigen');
assert(layout.includes('intern-whatsapp-link')&&layout.includes('/intern/whatsapp/')&&layout.includes("action=menu_access"),'Der persönliche WhatsApp-Menüpunkt fehlt in der linken Navigation');
assert(api.includes("['christian','marc','holger']"),'Der persönliche WhatsApp-Menüpunkt muss für Christian, Marc und Holger freigegeben sein');
for(const token of ['WhatsApp Business','wa-profile-select','wa-connect','wa-messages','/intern/whatsapp-account.js'])assert(accountPage.includes(token),`Eigene WhatsApp-Kontoseite unvollständig: ${token}`);
assert(accountPage.indexOf('Nachrichten und Dateien') < accountPage.indexOf('wa-account-card'),'Kontostatus muss am Seitenende unterhalb von Versand und Eingang stehen');
assert(accountPage.includes('<details class="wa-card wa-account-card">'),'Kontostatus muss standardmäßig zugeklappt sein');
assert(accountClient.includes('selected_expert')&&accountClient.includes('complete_signup')&&accountClient.includes('Die WhatsApp-Konten anderer Bearbeiter bleiben getrennt.'),'Die eigene Kontoseite muss Profilwahl, Meta-Verbindung und Kontentrennung enthalten');
for(const token of ['wa-recipient-phone','wa-message-text','wa-message-send','wa-phonebook-search','wa-case-search'])assert(accountPage.includes(token),`Versandfeld der WhatsApp-Kontoseite unvollständig: ${token}`);
assert(accountClient.includes('PHONEBOOK_API')&&accountClient.includes('?action=list')&&accountClient.includes('action=search_cases')&&accountClient.includes('action=send_message'),'Telefonbuch-, Akten- oder Direktversand-Anbindung fehlt');
assert(accountClient.includes("approved.find(t=>t.key==='allgemein')||approved.find(t=>t.key==='meta_start')")&&accountClient.includes('ist für den Erstkontakt vorausgewählt'),'Ein freigegebener Textbaustein muss beim Erstkontakt automatisch vorausgewählt werden');
assert(templateApi.includes("'meta_start' =>")&&templateApi.includes("'name'=>'hello_world'")&&templateApi.includes("$key==='meta_start'?'en_US'")&&templateApi.includes("'parameters'=>0"),'Die parameterlose Meta-Startvorlage fehlt');
assert(api.includes('function waSendText')&&api.includes("$action === 'send_message'")&&api.includes("'type'=>'text'"),'Freier WhatsApp-Textversand fehlt serverseitig');
assert(!accountPage.includes('wa-webhook-setup')&&!accountPage.includes('Verifizierungstoken')&&!accountClient.includes('webhook_setup'),'Webhook-Geheimnisse dürfen auf der persönlichen WhatsApp-Seite nicht angezeigt werden');
assert(client.includes('const escape=')&&client.includes('escape(row.original_name||row.caption'),'WhatsApp-Inhalte müssen vor der Darstellung maskiert werden');
assert(accountClient.includes('META_REENGAGEMENT_CODE=131047')&&accountClient.includes('metaErrorCode(text)===META_REENGAGEMENT_CODE')&&!accountClient.includes('/unknown error/i.test'),'Nur der echte Meta-Code 131047 darf als 24-Stunden-Fensterproblem angezeigt werden, sonst wird der wahre Fehler (z. B. ein ungültiger Zugriffstoken) verschleiert');
assert(!templateApi.includes("stripos($message, 'unknown error')"),'Ein generischer Meta-Fehler beim Textbaustein-Versand darf nicht pauschal als 24-Stunden-Fensterproblem umgedeutet werden');
console.log('whatsapp_case_test: ok');
