import fs from 'node:fs';
const fromProject=path=>new URL(`../${path}`,import.meta.url);
const page=fs.readFileSync(fromProject('src/pages/intern/versicherungsfaelle/index.astro'),'utf8');
const api=fs.readFileSync(fromProject('public/intern/api/whatsapp-case.php'),'utf8');
const client=fs.readFileSync(fromProject('public/intern/whatsapp-case.js'),'utf8');
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
for(const token of ['vf-wa-panel','vf-wa-vn','vf-wa-sanierer','vf-wa-send','vf-wa-connect','WhatsApp verbinden','WhatsApp noch nicht verbunden','/intern/whatsapp-case.js'])assert(page.includes(token),`Portalbestandteil fehlt: ${token}`);
assert(!api.includes("'susanne' =>")&&!api.includes("'jens' =>"),'Susanne und Jens dürfen kein WhatsApp-Profil erhalten');
for(const token of ['christian','holger','marc','WHATSAPP_CHRISTIAN_PHONE_NUMBER_ID','WHATSAPP_HOLGER_PHONE_NUMBER_ID','WHATSAPP_MARC_PHONE_NUMBER_ID'])assert(api.includes(token),`Profilkonfiguration fehlt: ${token}`);
for(const number of ['+491604092134','+491731645162','+4923926592751'])assert(api.includes(`'number'=>'${number}'`),`WhatsApp-Business-Nummer fehlt: ${number}`);
assert(!api.includes('+491712119777'),'Marcs frühere Mobilnummer darf nicht mehr als WhatsApp-Business-Nummer verwendet werden');
assert(api.includes('Portal-App noch nicht mit Meta verbunden'),'Ein fehlendes Portal-App-Setup darf nicht als fehlende WhatsApp-Business-Registrierung dargestellt werden');
for(const token of ['whatsapp_profile_connections','WHATSAPP_META_APP_ID','WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID','waEncryptToken','is_on_biz_app','complete_signup','subscribed_apps'])assert(api.includes(token),`Sichere Meta-Selbstverbindung fehlt: ${token}`);
for(const token of ['X_HUB_SIGNATURE_256',"hash_hmac('sha256'",'last_outbound_wamid','valid_until>=NOW()','unassigned','gd'])void token;
assert(api.includes('HTTP_X_HUB_SIGNATURE_256')&&api.includes("hash_hmac('sha256'"),'Webhook-Signaturprüfung fehlt');
assert(api.includes('last_outbound_wamid')&&api.includes('valid_until>=NOW()'),'Kontextgebundene Fallzuordnung fehlt');
assert(api.includes("status'=>'unassigned'")||api.includes("'unassigned'"),'Nicht eindeutige Eingänge müssen unzugeordnet bleiben');
assert(api.includes("$action === 'assign_message'")&&client.includes('Aktivem Fall zuordnen'),'Manuelle Zuordnung eines uneindeutigen WhatsApp-Eingangs fehlt');
assert(api.includes("'02_Fotos'")&&api.includes("'04_Rechnungen_KVA'")&&api.includes("'07_Korrespondenz'"),'Drive-Zielordner fehlen');
assert(client.includes("meta.mobil,meta.telefon")&&client.includes("meta.sanierer_mobil,meta.sanierer_telefon"),'VN- und Sanierer-Rufnummern werden nicht getrennt übernommen');
assert(client.includes('connection?.connected'),'Versand darf ohne Meta-Verbindung nicht aktiv werden');
assert(client.includes('whatsapp_business_app_onboarding')&&client.includes('WA_EMBEDDED_SIGNUP'),'Meta-Coexistence muss aus dem Portal geführt werden');
assert(client.includes('const escape=')&&client.includes('escape(row.original_name||row.caption'),'WhatsApp-Inhalte müssen vor der Darstellung maskiert werden');
console.log('whatsapp_case_test: ok');
